In [1]:
import pandas as pd
import os

In [2]:
DATA_PATH = "../data/raw/"

In [3]:
files = os.listdir(DATA_PATH)

for file in files:
    print(file)

olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [4]:
customers = pd.read_csv(
    DATA_PATH + "olist_customers_dataset.csv"
)

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [5]:
customers.shape

(99441, 5)

In [6]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [7]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [8]:
customers.duplicated().sum()

np.int64(0)

In [9]:
customers.duplicated().sum()

np.int64(0)

In [10]:
customers["customer_id"].nunique()

99441

In [11]:
customers["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [12]:
customers["customer_city"].nunique()

4119

In [13]:
orders = pd.read_csv(
    DATA_PATH + "olist_orders_dataset.csv"
)

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [14]:
orders.shape

(99441, 8)

In [15]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [16]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [17]:
orders.duplicated().sum()

np.int64(0)

In [18]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [19]:
orders["order_id"].nunique()

99441

In [20]:
orders["customer_id"].nunique()

99441

In [21]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

orders[date_columns].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [22]:
for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

orders[date_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [24]:
orders[date_columns].isnull().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [25]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [27]:
orders.groupby("order_status")[
    [
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].apply(lambda group: group.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [28]:
delivered_missing_dates = orders[
    (orders["order_status"] == "delivered") &
    (
        orders["order_approved_at"].isnull() |
        orders["order_delivered_carrier_date"].isnull() |
        orders["order_delivered_customer_date"].isnull()
    )
]

delivered_missing_dates[
    [
        "order_id",
        "order_status",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
]

,order_id,order_status,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
5323,e04abd8149ef81b95221e88f6ed9ab6a,delivered,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,delivered,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,delivered,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
22663,5cf925b116421afa85ee25e99b4c34fb,delivered,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,delivered,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,delivered,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,delivered,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,delivered,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
48401,7002a78c79c519ac54022d4f8a65e6e8,delivered,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,delivered,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,delivered,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,delivered,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,delivered,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
73222,2aa91108853cecb43c84a5dc5b277475,delivered,2017-09-29 09:07:16,NaT,2017-11-20 19:44:47,2017-11-14
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
84999,2babbb4b15e6d2dfe95e2de765c97bce,delivered,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [30]:
delivered_orders = orders[
    orders["order_status"] == "delivered"
]

print("Total delivered orders:", len(delivered_orders))

print(
    "Missing approval timestamps:",
    delivered_orders["order_approved_at"].isnull().sum()
)

print(
    "Missing carrier timestamps:",
    delivered_orders["order_delivered_carrier_date"].isnull().sum()
)

print(
    "Missing customer delivery timestamps:",
    delivered_orders["order_delivered_customer_date"].isnull().sum()
)

Total delivered orders: 96478
Missing approval timestamps: 14
Missing carrier timestamps: 2
Missing customer delivery timestamps: 8

In [31]:
print(
    "First order purchase date:",
    orders["order_purchase_timestamp"].min()
)

print(
    "Last order purchase date:",
    orders["order_purchase_timestamp"].max()
)

First order purchase date: 2016-09-04 21:15:19
Last order purchase date: 2018-10-17 17:30:18

In [32]:
orders["purchase_month"] = (
    orders["order_purchase_timestamp"]
    .dt.to_period("M")
)

monthly_orders = (
    orders.groupby("purchase_month")["order_id"]
    .count()
    .reset_index(name="total_orders")
)

monthly_orders

   purchase_month  total_orders
0         2016-09             4
1         2016-10           324
2         2016-12             1
3         2017-01           800
4         2017-02          1780
5         2017-03          2682
6         2017-04          2404
7         2017-05          3700
8         2017-06          3245
9         2017-07          4026
10        2017-08          4331
11        2017-09          4285
12        2017-10          4631
13        2017-11          7544
14        2017-12          5673
15        2018-01          7269
16        2018-02          6728
17        2018-03          7211
18        2018-04          6939
19        2018-05          6873
20        2018-06          6167
21        2018-07          6292
22        2018-08          6512
23        2018-09            16
24        2018-10             4

In [34]:
print("Earliest purchase:", orders["order_purchase_timestamp"].min())
print("Latest purchase:", orders["order_purchase_timestamp"].max())

Earliest purchase: 2016-09-04 21:15:19
Latest purchase: 2018-10-17 17:30:18

In [35]:
orders.groupby(
    orders["order_purchase_timestamp"].dt.to_period("M")
).agg(
    first_order_date=("order_purchase_timestamp", "min"),
    last_order_date=("order_purchase_timestamp", "max"),
    total_orders=("order_id", "count")
)

                            first_order_date     last_order_date  total_orders
order_purchase_timestamp
2016-09                  2016-09-04 21:15:19 2016-09-15 12:16:38             4
2016-10                  2016-10-02 22:07:52 2016-10-22 08:25:27           324
2016-12                  2016-12-23 23:16:47 2016-12-23 23:16:47             1
2017-01                  2017-01-05 11:56:06 2017-01-31 23:37:58           800
2017-02                  2017-02-01 00:04:17 2017-02-28 23:47:08          1780
2017-03                  2017-03-01 00:01:30 2017-03-31 23:54:45          2682
2017-04                  2017-04-01 00:54:10 2017-04-30 23:48:13          2404
2017-05                  2017-05-01 01:18:22 2017-05-31 22:59:52          3700
2017-06                  2017-06-01 00:05:38 2017-06-30 23:20:08          3245
2017-07                  2017-07-01 00:04:15 2017-07-31 23:55:27          4026
2017-08                  2017-08-01 00:02:01 2017-08-31 23:55:57          4331
2017-09                  2017-09-01 00:03:50 2017-09-30 23:59:15          4285
2017-10                  2017-10-01 00:03:33 2017-10-31 23:50:58          4631
2017-11                  2017-11-01 00:12:34 2017-11-30 23:36:03          7544
2017-12                  2017-12-01 00:01:14 2017-12-31 23:29:31          5673
2018-01                  2018-01-01 02:48:41 2018-01-31 23:58:22          7269
2018-02                  2018-02-01 00:24:55 2018-02-28 23:57:55          6728
2018-03                  2018-03-01 00:00:00 2018-03-31 23:54:10          7211
2018-04                  2018-04-01 00:11:32 2018-04-30 23:47:26          6939
2018-05                  2018-05-01 00:02:11 2018-05-31 23:51:24          6873
2018-06                  2018-06-01 00:39:55 2018-06-30 23:59:49          6167
2018-07                  2018-07-01 00:25:07 2018-07-31 23:54:20          6292
2018-08                  2018-08-01 00:02:17 2018-08-31 16:13:44          6512
2018-09                  2018-09-03 09:06:57 2018-09-29 09:13:03            16
2018-10                  2018-10-01 15:30:09 2018-10-17 17:30:18             4